name: Publish

on: [push]

jobs:
  test:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn
      - run: yarn test
      - run: yarn buildpackage

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: artifacts
          path: ./dist

      - name: Publish package
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          yarn publish --access public
